import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#F3F4FF] antialiased h-full mx-auto px-4 pb-8`}
      >
        <div className="min-h-screen flex flex-col">
          {/* <Navbar /> */}
          <main className="flex-1 grow grid">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
